<html>
<head>
<link rel="stylesheet" href="../css/wro.css"/>
</head>
<body>
	<div class="container">
		<h2>Please Confirm</h2>

		<p>
			Do you authorize "${authorizationRequest.clientId}" at "${authorizationRequest.redirectUri}" to access your protected resources
			with scope ${authorizationRequest.scope?join(", ")}.
			
		</p>
		<form id='confirmationForm' name='confirmationForm' action='../oauth/authorize' method='post'>
			<input name='user_oauth_approval' value='true' type='hidden'/>
			<input type='hidden' name='${_csrf.parameterName}' value='${_csrf.token}' />
			<input type='hidden' name='${authorizationRequest.scope?join(", ")}' value='true' >
			CSRF %scopes%<label><input name='authorize' value='Authorize' type='submit'/></label>
		</form>
		
		<form id='denialForm' name='denialForm' action='../oauth/authorize' method='post'>
			<input name='user_oauth_approval' value='false' type='hidden'/>
			<input type='hidden' name='${_csrf.parameterName}' value='${_csrf.token}' />
			<input type='hidden' name='${authorizationRequest.scope?join(", ")}' value='false' >
			CSRF<label><input name='deny' value='Deny' type='submit'/></label>
		</form>
		
		generated by fahiz
	</div>
	<script src="../js/wro.js"	type="text/javascript"></script>
</body>
</html>