/*
 #   by Sameera @ zaizi.com
 #   for Sensefy Search
 #   main configuration js file to handle all global variables, languages and route provider
 */

(function () {
    window.translate = null;

    angular.module('SensefyConfiguration', ['ngCookies', 'ngResource', 'ngSanitize', 'ngRoute', 'pascalprecht.translate'])
        .constant('SensefyAPIUrl', 'service/api/')
        .constant('SensefyTokenCreatePath', 'token/create')
        .constant('SensefySemanticSearchKeywordBased', 'keywordSearch')
        .constant('SensefyEntityDrivenSearch', 'entityDrivenSearch')
        .constant('SensefyGetEntitiesByDoc', 'showEntitiesByDocId')
        .constant('SensefyPreviewDoc', 'docs/preview')
        .constant('DEBUGmode', true)   //  Sensefy debuger mode is enabled with Boolean:true;
        .constant('SensefySmartAutocompletePhase1', 'autocomplete/1')
        .constant('SensefySmartAutocompletePhase2', 'autocomplete/2')
        .constant('SensefySmartAutocompletePhase3', 'autocomplete/3')
        .constant('SensefyDocsPreview', 'docs/preview')
        .constant('SensefyMlt', 'docs/mlt')
        .constant('SensefyFacetsPerGroup', 2)
        .constant('SensefyUNIXdate', 1000)
        .constant('SensefySearchLogin', 'logout')
        .constant('SensefySearchIsSemantic', true)
        .constant('SensefySearchIsClustering', true)
        .constant('SensefyDocSecurity', true)
        .constant('SensefySearchResponseFailedIsLogout', true)
        .constant('SensefySortOptions', [
            {
                'id': 1,
                'sortOption': 'Relevance',
                'sortId': 'score',
                'defaultSort': 'DESC'
            }, {
                'id': 2,
                'sortOption': 'Name',
                'sortId': 'name_sort',
                'defaultSort': 'ASC'
            }, {
                'id': 3,
                'sortOption': 'Title',
                'sortId': 'title_sort',
                'defaultSort': 'ASC'
            }, {
                'id': 4,
                'sortOption': 'Created',
                'sortId': 'ds_creation_date',
                'defaultSort': 'DESC'
            }, {
                'id': 5,
                'sortOption': 'Modified',
                'sortId': 'ds_last_modified',
                'defaultSort': 'DESC'
            }, {
                'id': 6,
                'sortOption': 'Creator',
                'sortId': 'ds_creator_sort',
                'defaultSort': 'ASC'
            }, {
                'id': 7,
                'sortOption': 'Modifier',
                'sortId': 'ds_last_modifier_sort',
                'defaultSort': 'ASC'
            }
        ])
        .constant('SensefyTranslations', {
            'en-us': {
                'language': 'Language',
                'english': 'English',
                'spanish': 'Spanish',
                'settings': 'Settings',
                'resultsperpage': '-Results per page-',
                'savesearch': 'Save Search',
                'savealerts': 'Save Alerts',
                'sharesearch': 'Share Search',
                'sortby': 'Sort by',
                'relevance': 'Relevance',
                'filterby': 'Filter by',
                'All': 'All',
                'txtUsername': 'Username',
                'txtPassword': 'Password',
                'txtCaptcha': 'Captcha',
                'msgCaptcha': 'System detected that number of failed login attempts!. Please fill the text from image to verify.',
                'login': 'Login',
                'logout': 'Logout',
                'errorBadCredentials': 'Bad credentials. Try again!',
                'errorBadUsernameOrPassword': 'Username or Password are incorrect. Please check them',
                'errorBadUsernameOrPasswordOrCaptcha': 'Username or Password or Captcha are incorrect. Please check them',
                'errorCaptch': 'Captcha is incorrect. Please check',
                'errorExpiredSession': 'Session expired. Please login again',
                'errorAPINotAvailable': 'Sensefy API is not available at this moment',
                'txtEnterTextToSearch': 'Please enter text to search',
                'txtEntities': 'Entities',
                'txtEntityTypes': 'Entity Types',
                'txtDocumentTitles': 'Document titles',
                'txtDocumentSuggestions': 'Suggestions',
                'txtNoSuggestions': 'No suggestions',
                'txtDocumentsFound': 'Showing results {{docStart}}-{{docEnd}} of {{documents}}.',//Showing results 1-10 of 1404.
                'txtDocumentsCountFound': 'documents found',
                'txtNoDocumentsFound': 'No document found.',
                'txtDidYouMean': 'Did you mean:',
                'txtSortByTitle': 'Sort by Title',
                'txtSimilarityOfDocuments': 'Similarity of Documents',
                'txtNoSimilarDocumentsFound': 'No similar documents found',
                'txtSimilarDocuments': 'Similar documents',
                'txtSeedDocument': 'Seed document',
                'txtLow': 'Low',
                'txtHigh': 'High',
                'today': 'Today',
                'yesterday': 'Yesterday',
                'last_week': 'Last Week',
                'last_month': 'Last Month',
                'firstPage': 'First',
                'lastPage': 'Last',
                'nextPage': 'Next',
                'previousPage': 'Previous',
                'Creator': 'Creator',
                'Mimetype': 'Document Type',
                'Language': 'Language',
                'Size': 'Size',
                'Last Modified Date': 'Last Modified Date',
                'Creation Date': 'Creation Date',
                'sorting.hint': 'Sorting options',
                'Relevance': 'Relevance',
                'Name': 'Name',
                'Title': 'Title',
                'Created': 'Created',
                'Modified': 'Modified',
                'Modifier': 'Modifier',
                'txtBackBtn': 'Back',
                'txtLanguages': 'Sensefy offered in ',
                'data.moreMetadata': 'More metadata',
                'data.size': 'Size',
                'data.datasource': 'Datasource',
                'data.modifier': 'Modifier',
                'data.modified': 'Modified',
                'data.language': 'Language',
                'data.author': 'Author',
                'data.created': 'Creation Date',
                'preview.page': 'Page',
                'preview.of': 'of',
                'preview.nopreview': 'No preview available',
                'preview.notsupported': 'Preview not supported yet',
                'preview.metadata': 'Metadata',
                'preview.name': 'Name',
                'preview.title': 'Title',
                'preview.description': 'Description',
                'preview.author': 'Author',
                'preview.datasource': 'Datasource',
                'preview.datasource_type': 'Datasource type',
                'preview.created': 'Creation Date',
                'preview.creator': 'Creator',
                'preview.modified': 'Last Modified',
                'preview.modifier': 'Last Modifier',
                'preview.language': 'Language',
                'preview.mimetype': 'Mimetype',
                'preview.size': 'Size',
                'preview.gotofolder': 'Go to folder container',
                'preview.close': 'Close',
                'preview.error': 'Error loading the preview',
                'mlt.hint': 'More like this',
                'application/json': 'JSON',
                'application/eps': 'EPS Type PostScript',
                'image/jp2': 'JPEG 2000 Image',
                'application/vnd.ms-project': 'Microsoft Project',
                'image/vnd.adobe.photoshop': 'Adobe Photoshop',
                'image/vnd.adobe.premiere': 'Adobe Premiere',
                'audio/vnd.adobe.soundbooth': 'Adobe SoundBooth',
                'application/vnd.adobe.aftereffects.project': 'Adobe AfterEffects Project',
                'application/vnd.adobe.aftereffects.template': 'Adobe AfterEffects Template',
                'application/framemaker': 'Adobe FrameMaker',
                'application/pagemaker': 'Adobe PageMaker',
                'application/remote-printing': 'Printer Text File',
                'text/plain': 'Plain Text',
                'text/csv': 'Comma Separated Values (CSV)',
                'text/html': 'HTML',
                'text/mediawiki': 'MediaWiki Markup',
                'application/xhtml+xml': 'XHTML',
                'application/postscript': 'PostScript',
                'application/illustrator': 'Adobe Illustrator File',
                'audio/x-aiff': 'AIFF Audio',
                'application/acp': 'Alfresco Content Package',
                'application/vnd.visio': 'Microsoft Visio',
                'application/vnd.adobe.xdp+xml': 'Adobe Acrobat XML Data Package',
                'audio/basic': 'Basic Audio',
                'video/ogg': 'Ogg Video',
                'audio/ogg': 'Ogg Audio',
                'audio/vorbis': 'Ogg Vorbis Audio',
                'application/ogg': 'Ogg Multiplex',
                'audio/x-flac': 'FLAC Audio',
                'video/webm': 'WebM Video',
                'video/x-msvideo': 'MS Video',
                'video/x-ms-asf': 'MS ASF Streaming Video',
                'video/x-ms-wmv': 'MS WMV Streaming Video',
                'audio/x-ms-wma': 'MS WMA Streaming Audio',
                'video/x-rad-screenplay': 'RAD Screen Display',
                'application/octet-stream': 'Binary File (Octet Stream)',
                'application/x-dosexec': 'Binary File',
                'image/cgm': 'CGM Image',
                'application/java': 'Java Class',
                'text/css': 'Style Sheet',
                'application/wordperfect': 'WordPerfect',
                'text/xml': 'XML',
                'image/gif': 'GIF Image',
                'application/x-gtar': 'GZIP Tarball',
                'application/x-gzip': 'GZIP',
                'text/calendar': 'iCalendar File',
                'image/ief': 'IEF Image',
                'image/bmp': 'Bitmap Image',
                'image/x-ms-bmp': 'MS Bitmap Image',
                'image/jpeg': 'JPEG Image',
                'image/svg+xml': 'Scalable Vector Graphics Image',
                'image/x-raw-adobe': 'Adobe Digital Negative Image',
                'image/x-raw-hasselblad': 'Hasselblad RAW Image',
                'image/x-raw-fuji': 'Fuji RAW Image',
                'image/x-raw-canon': 'Canon RAW Image',
                'image/x-raw-kodak': 'Kodak RAW Image',
                'image/x-raw-minolta': 'Minolta RAW Image',
                'image/x-raw-nikon': 'Nikon RAW Image',
                'image/x-raw-olympus': 'Olympus RAW Image',
                'image/x-raw-pentax': 'Pentax RAW Image',
                'image/x-raw-sony': 'Sony RAW Image',
                'image/x-raw-sigma': 'Sigma RAW Image',
                'image/x-raw-panasonic': 'Panasonic RAW Image',
                'image/x-raw-leica': 'Leica RAW Image',
                'image/x-raw-red': 'RED RAW Image',
                'application/x-javascript': 'JavaScript',
                'application/x-latex': 'LaTeX',
                'application/x-troff-man': 'Man Page',
                'video/mpeg': 'MPEG Video',
                'audio/mpeg': 'MPEG Audio',
                'audio/mp4': 'MPEG4 Audio',
                'video/mp4': 'MPEG4 Video',
                'video/x-m4v': 'MPEG4 Video (m4v)',
                'video/mpeg2': 'MPEG2 Video',
                'video/mp2t': 'MPEG Transport Stream',
                'video/quicktime': 'Quicktime Video',
                'video/3gpp': '3G Video',
                'video/3gpp2': '3G2 Video',
                'video/x-sgi-movie': 'SGI Video',
                'image/x-portable-bitmap': 'Portable Bitmap',
                'application/pdf': 'Adobe PDF Document',
                'image/x-portable-graymap': 'Greymap Image',
                'image/png': 'PNG Image',
                'image/x-portable-anymap': 'Anymap Image',
                'image/x-portable-pixmap': 'Pixmap Image',
                'image/x-cmu-raster': 'Raster Image',
                'image/x-rgb': 'RGB Image',
                'application/rtf': 'Rich Text Format',
                'text/richtext': 'Rich Text',
                'text/sgml': 'SGML (Human Readable)',
                'application/sgml': 'SGML (Machine Readable)',
                'application/x-sh': 'Shell Script',
                'application/vnd.adobe.air-application-installer-package+zip': 'Adobe AIR',
                'application/x-shockwave-flash': 'Shockwave Flash',
                'video/x-flv': 'Flash Video',
                'application/x-fla': 'Flash Source',
                'application/dita+xml': 'DITA',
                'application/x-tar': 'Tarball',
                'application/x-tex': 'Tex',
                'application/x-texinfo': 'Tex Info',
                'image/tiff': 'TIFF Image',
                'text/tab-separated-values': 'Tab Separated Values',
                'audio/x-wav': 'WAV Audio',
                'x-world/x-vrml': 'VRML',
                'image/x-xbitmap': 'XBitmap Image',
                'image/x-xpixmap': 'XPixmap Image',
                'image/x-xwindowdump': 'XWindow Dump',
                'application/x-compress': 'Z Compress',
                'application/zip': 'ZIP',
                'application/vnd.android.package-archive': 'Android Package',
                'image/vnd.dwg': 'AutoCAD Drawing',
                'image/x-dwt': 'AutoCAD Template',
                'message/rfc822': 'EMail',
                'application/vnd.ms-outlook': 'Microsoft Outlook Message',
                'application/msword': 'Microsoft Word',
                'application/vnd.ms-powerpoint': 'Microsoft PowerPoint',
                'application/vnd.ms-excel': 'Microsoft Excel',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'Microsoft Word 2007',
                'application/vnd.ms-word.document.macroenabled.12': 'Microsoft Word 2007 macro-enabled document',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.template': 'Microsoft Word 2007 template',
                'application/vnd.ms-word.template.macroenabled.12': 'Microsoft Word 2007 macro-enabled document template',
                'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'Microsoft PowerPoint 2007',
                'application/vnd.ms-powerpoint.presentation.macroenabled.12': 'Microsoft PowerPoint 2007 macro-enabled presentation',
                'application/vnd.openxmlformats-officedocument.presentationml.slideshow': 'Microsoft PowerPoint 2007 slide show',
                'application/vnd.ms-powerpoint.slideshow.macroenabled.12': 'Microsoft PowerPoint 2007 macro-enabled slide show',
                'application/vnd.openxmlformats-officedocument.presentationml.template': 'Microsoft PowerPoint 2007 template',
                'application/vnd.ms-powerpoint.template.macroenabled.12': 'Microsoft PowerPoint 2007 macro-enabled presentation template',
                'application/vnd.ms-powerpoint.addin.macroenabled.12': 'Microsoft PowerPoint 2007 add-in',
                'application/vnd.openxmlformats-officedocument.presentationml.slide': 'Microsoft PowerPoint 2007 slide',
                'application/vnd.ms-powerpoint.slide.macroenabled.12': 'Microsoft PowerPoint 2007 macro-enabled slide',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'Microsoft Excel 2007',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.template': 'Microsoft Excel template 2007',
                'application/vnd.ms-excel.sheet.macroenabled.12': 'Microsoft Excel 2007 macro-enabled workbook',
                'application/vnd.ms-excel.template.macroenabled.12': 'Microsoft Excel 2007 macro-enabled workbook template',
                'application/vnd.ms-excel.addin.macroenabled.12': 'Microsoft Excel 2007 add-in',
                'application/vnd.ms-excel.sheet.binary.macroenabled.12': 'Microsoft Excel 2007 binary workbook',
                'application/x-zip': 'Adobe Flex Project File',
                'application/x-indesign': 'Adobe InDesign Document',
                'application/vnd.apple.keynote': 'Apple iWork Keynote',
                'application/vnd.apple.pages': 'Apple iWork Pages',
                'application/vnd.apple.numbers': 'Apple iWork Numbers',
                'text/x-markdown': 'Markdown',
                'application/rss+xml': 'RSS',
                'text/x-java-source': 'Java Source File',
                'text/x-jsp': 'Java Server Page',
                'application/java-archive': 'Java Archive',
                'application/x-rar-compressed': 'RAR Archive',
                'application/vnd.oasis.opendocument.text': 'OpenDocument Text (OpenOffice 2.0)',
                'application/vnd.oasis.opendocument.text-template': 'OpenDocument Text Template',
                'application/vnd.oasis.opendocument.text-web': 'HTML Document Template',
                'application/vnd.oasis.opendocument.text-master': 'OpenDocument Master Document',
                'application/vnd.oasis.opendocument.graphics': 'OpenDocument Drawing',
                'application/vnd.oasis.opendocument.graphics-template': 'OpenDocument Drawing Template',
                'application/vnd.oasis.opendocument.presentation': 'OpenDocument Presentation',
                'application/vnd.oasis.opendocument.presentation-template': 'OpenDocument Presentation Template',
                'application/vnd.oasis.opendocument.spreadsheet': 'OpenDocument Spreadsheet',
                'application/vnd.oasis.opendocument.spreadsheet-template': 'OpenDocument Spreadsheet Template',
                'application/vnd.oasis.opendocument.chart': 'OpenDocument Chart',
                'application/vnd.oasis.opendocument.formula': 'OpenDocument Formula',
                'application/vnd.oasis.opendocument.database': 'OpenDocument Database',
                'application/vnd.oasis.opendocument.image': 'OpenDocument Image',
                'application/vnd.sun.xml.calc': 'OpenOffice 1.0/StarOffice6.0 Calc 6.0',
                'application/vnd.sun.xml.calc.template': 'OpenOffice 1.0/StarOffice6.0 Calc 6.0 Template',
                'application/vnd.sun.xml.draw': 'OpenOffice 1.0/StarOffice6.0 Draw 6.0',
                'application/vnd.sun.xml.impress': 'OpenOffice 1.0/StarOffice6.0 Impress 6.0',
                'application/vnd.sun.xml.impress.template': 'OpenOffice 1.0/StarOffice6.0 Impress 6.0 Template',
                'application/vnd.sun.xml.writer': 'OpenOffice 1.0/StarOffice6.0 Writer 6.0',
                'application/vnd.sun.xml.writer.template': 'OpenOffice 1.0/StarOffice6.0 Writer 6.0 Template',
                'application/vnd.stardivision.draw': 'StarDraw 5.x',
                'application/vnd.stardivision.calc': 'StarCalc 5.x',
                'application/vnd.stardivision.impress': 'StarImpress 5.x',
                'application/vnd.stardivision.impress-packed': 'StarImpress Packed 5.x',
                'application/vnd.stardivision.chart': 'StaChart 5.x',
                'application/vnd.stardivision.writer': 'StarWriter 5.x',
                'application/vnd.stardivision.writer-global': 'StarWriter 5.x global',
                'application/vnd.stardivision.math': 'StarMath 5.x',
                'aa': 'Afar',
                'ab': 'Abkhazian',
                'ae': 'Avestan',
                'af': 'Afrikaans',
                'ak': 'Akan',
                'am': 'Amharic',
                'an': 'Aragonese',
                'ar': 'Arabic',
                'as': 'Assamese',
                'av': 'Avaric',
                'ay': 'Aymara',
                'az': 'Azerbaijani',
                'ba': 'Bashkir',
                'be': 'Belarusian',
                'bg': 'Bulgarian',
                'bh': 'Bihari languages',
                'bi': 'Bislama',
                'bm': 'Bambara',
                'bn': 'Bengali',
                'bo': 'Tibetan',
                'br': 'Breton',
                'bs': 'Bosnian',
                'ca': 'Catalan',
                'ce': 'Chechen',
                'ch': 'Chamorro',
                'co': 'Corsican',
                'cr': 'Cree',
                'cs': 'Czech',
                'cu': 'Church Slavic',
                'cv': 'Chuvash',
                'cy': 'Welsh',
                'da': 'Danish',
                'de': 'German',
                'dv': 'Dhivehi',
                'dz': 'Dzongkha',
                'ee': 'Ewe',
                'el': 'Modern Greek',
                'en': 'English',
                'en-GB': 'British English',
                'en_US': 'English (US)',
                'eo': 'Esperanto',
                'es': 'Spanish',
                'es-ES': 'Spanish (Spain)',
                'et': 'Estonian',
                'eu': 'Basque',
                'fa': 'Persian',
                'ff': 'Fulah',
                'fi': 'Finnish',
                'fj': 'Fijian',
                'fo': 'Faroese',
                'fr': 'French',
                'fy': 'Western Frisian',
                'ga': 'Irish',
                'gd': 'Scottish Gaelic',
                'gl': 'Galician',
                'gn': 'Guarani',
                'gu': 'Gujarati',
                'gv': 'Manx',
                'ha': 'Hausa',
                'he': 'Hebrew',
                'hi': 'Hindi',
                'ho': 'Hiri Motu',
                'hr': 'Croatian',
                'ht': 'Haitian',
                'hu': 'Hungarian',
                'hy': 'Armenian',
                'hz': 'Herero',
                'ia': 'Interlingua',
                'id': 'Indonesian',
                'ie': 'Interlingue',
                'ig': 'Igbo',
                'ii': 'Sichuan Yi',
                'ik': 'Inupiaq',
                'io': 'Ido',
                'is': 'Icelandic',
                'it': 'Italian',
                'iu': 'Inuktitut',
                'ja': 'Japanese',
                'jv': 'Javanese',
                'ka': 'Georgian',
                'kg': 'Kongo',
                'ki': 'Kikuyu',
                'kj': 'Kuanyama',
                'kk': 'Kazakh',
                'kl': 'Kalaallisut',
                'km': 'Central Khmer',
                'kn': 'Kannada',
                'ko': 'Korean',
                'kr': 'Kanuri',
                'ks': 'Kashmiri',
                'ku': 'Kurdish',
                'kv': 'Komi',
                'kw': 'Cornish',
                'ky': 'Kirghiz',
                'la': 'Latin',
                'lb': 'Luxembourgish',
                'lg': 'Ganda',
                'li': 'Limburgan',
                'ln': 'Lingala',
                'lo': 'Lao',
                'lt': 'Lithuanian',
                'lu': 'Luba-Katanga',
                'lv': 'Latvian',
                'mg': 'Malagasy',
                'mh': 'Marshallese',
                'mi': 'Maori',
                'mk': 'Macedonian',
                'ml': 'Malayalam',
                'mn': 'Mongolian',
                'mr': 'Marathi',
                'ms': 'Malay',
                'mt': 'Maltese',
                'my': 'Burmese',
                'na': 'Nauru',
                'nb': 'Norwegian Bokmål',
                'nd': 'North Ndebele',
                'ne': 'Nepali',
                'ng': 'Ndonga',
                'nl': 'Dutch',
                'nn': 'Norwegian Nynorsk',
                'no': 'Norwegian',
                'nr': 'South Ndebele',
                'nv': 'Navajo',
                'ny': 'Nyanja',
                'oc': 'Occitan',
                'oj': 'Ojibwa',
                'om': 'Oromo',
                'or': 'Oriya',
                'os': 'Ossetian',
                'pa': 'Panjabi',
                'pi': 'Pali',
                'pl': 'Polish',
                'ps': 'Pushto',
                'pt': 'Portuguese',
                'qu': 'Quechua',
                'rm': 'Romansh',
                'rn': 'Rundi',
                'ro': 'Romanian',
                'ru': 'Russian',
                'rw': 'Kinyarwanda',
                'sa': 'Sanskrit',
                'sc': 'Sardinian',
                'sd': 'Sindhi',
                'se': 'Northern Sami',
                'sg': 'Sango',
                'sh': ' Serbo-Croatian',
                'si': 'Sinhala',
                'sk': 'Slovak',
                'sl': 'Slovenian',
                'sm': 'Samoan',
                'sn': 'Shona',
                'so': 'Somali',
                'sq': 'Albanian',
                'sr': 'Serbian',
                'ss': 'Swati',
                'st': 'Southern Sotho',
                'su': 'Sundanese',
                'sv': 'Swedish',
                'sw': 'Swahili',
                'ta': 'Tamil',
                'te': 'Telugu',
                'tg': 'Tajik',
                'th': 'Thai',
                'ti': 'Tigrinya',
                'tk': 'Turkmen',
                'tl': 'Tagalog',
                'tn': 'Tswana',
                'to': 'Tonga (Tonga Islands)',
                'tr': 'Turkish',
                'ts': 'Tsonga',
                'tt': 'Tatar',
                'tw': 'Twi',
                'ty': 'Tahitian',
                'ug': 'Uighur',
                'uk': 'Ukrainian',
                'ur': 'Urdu',
                'uz': 'Uzbek',
                've': 'Venda',
                'vi': 'Vietnamese',
                'vo': 'Volapük',
                'wa': 'Walloon',
                'wo': 'Wolof',
                'xh': 'Xhosa',
                'yi': 'Yiddish',
                'yo': 'Yoruba',
                'za': 'Zhuang',
                'zh': 'Chinese',
                'zu': 'Zulu',
                'Unknown': 'Unknown'
            },
            'es-es': {
                'language': 'Idioma',
                'english': 'Inglés',
                'spanish': 'Español',
                'settings': '-Settings-',
                'resultsperpage': '-Results per page-',
                'savesearch': '-Save Search-',
                'savealerts': '-Save Alerts-',
                'sharesearch': '-Share Search-',
                'sortby': '-Sort by-',
                'relevance': '-Relevance-',
                'filterby': '-Filter by-',
                'All': 'Todos',
                'txtUsername': 'Nombre de usuario',
                'txtPassword': 'Contraseña',
                'txtCaptcha': 'Captcha',
                'msgCaptcha': 'System detected that number of failed login attempts!. Please fill the text from image to verify.',
                'login': 'Iniciar sesión',
                'logout': 'Cerrar sesión',
                'errorBadCredentials': 'Credenciales inválidas. Inténtelo de nuevo',
                'errorBadUsernameOrPassword': 'Nombre de usuario o contraseña incorrectos. Por favor compruébelos',
                'errorBadUsernameOrPasswordOrCaptcha': 'Username or Password or Captcha are incorrect. Please check them',
                'errorCaptch': 'Captcha is incorrect. Please check',
                'errorExpiredSession': 'Sesión expirada. Inicie sesión de nuevo',
                'errorAPINotAvailable': 'Sensefy API no disponible en este momento',
                'txtEnterTextToSearch': 'Por favor introduzca el texto a buscar',
                'txtEntities': 'Entidades',
                'txtEntityTypes': 'Tipos de entidades',
                'txtDocumentTitles': 'Títulos de documentos',
                'txtDocumentSuggestions': 'Sugerencias',
                'txtNoSuggestions': 'No hay sugerencias',
                'txtDocumentsFound': 'Showing results(need to translate) {{docStart}}-{{docStart+docPerPage}} of {{documents}}.',
                'txtDocumentsCountFound': ' documentos encontrados',
                'txtNoDocumentsFound': 'No se han encontrado documentos.',
                'txtDidYouMean': 'Quisiste decir:',
                'txtSortByTitle': 'Ordenar por titulo',
                'txtSimilarityOfDocuments': 'Similitud de los documentos',
                'txtNoSimilarDocumentsFound': 'No se han encontrado documentos similares',
                'txtSimilarDocuments': 'Documentos similares',
                'txtSeedDocument': 'Documento semilla',
                'txtLow': 'Bajo',
                'txtHigh': 'Alto',
                'today': 'Hoy',
                'yesterday': 'Ayer',
                'last_week': 'Semana pasada',
                'last_month': 'Mes pasado',
                'firstPage': 'Primera',
                'lastPage': 'Última',
                'nextPage': 'Siguiente',
                'previousPage': 'Anterior',
                'Creator': 'Creador',
                'Mimetype': 'Tipo de documento',
                'Language': 'Lenguaje',
                'Size': 'Tamaño',
                'Last Modified Date': 'Fecha de última modificación',
                'Creation Date': 'Fecha de creación',
                'sorting.hint': 'Ordenación',
                'Relevance': 'Relevancia',
                'Name': 'Nombre',
                'Title': 'Título',
                'Created': 'Creado',
                'Modified': 'Modificado',
                'Modifier': 'Modificador',
                'txtBackBtn': 'Atrás',
                'txtLanguages': 'Sensefy disponible en ',
                'data.moreMetadata': 'Más metadatos',
                'data.size': 'Tamaño',
                'data.datasource': 'Origen de datos',
                'data.modifier': 'Modificador',
                'data.modified': 'Modificado',
                'data.language': 'Lenguaje',
                'data.author': 'Autor',
                'data.created': 'Fecha de creación',
                'preview.page': 'Página',
                'preview.of': 'de',
                'preview.nopreview': 'Vista previa no disponible',
                'preview.notsupported': 'Vista previa no soportada todavía',
                'preview.metadata': 'Metadatos',
                'preview.name': 'Nombre',
                'preview.title': 'Título',
                'preview.description': 'Descripción',
                'preview.author': 'Autor',
                'preview.datasource': 'Origen de datos',
                'preview.datasource_type': 'Tipo de origen de datos',
                'preview.created': 'Fecha de creación',
                'preview.creator': 'Creador',
                'preview.modified': 'Fecha última modificación',
                'preview.modifier': 'Modificador',
                'preview.language': 'Lenguaje',
                'preview.mimetype': 'Tipo MIME',
                'preview.size': 'Tamaño',
                'preview.gotofolder': 'Ir a carpeta contenedora',
                'preview.close': 'Cerrar',
                'preview.error': 'Error cargando la vista previa',
                'mlt.hint': 'Ver documentos similares',
                'application/json': 'JSON',
                'application/eps': 'EPS Type PostScript',
                'image/jp2': 'JPEG 2000 Image',
                'application/vnd.ms-project': 'Microsoft Project',
                'image/vnd.adobe.photoshop': 'Adobe Photoshop',
                'image/vnd.adobe.premiere': 'Adobe Premiere',
                'audio/vnd.adobe.soundbooth': 'Adobe SoundBooth',
                'application/vnd.adobe.aftereffects.project': 'Adobe AfterEffects Project',
                'application/vnd.adobe.aftereffects.template': 'Adobe AfterEffects Template',
                'application/framemaker': 'Adobe FrameMaker',
                'application/pagemaker': 'Adobe PageMaker',
                'application/remote-printing': 'Printer Text File',
                'text/plain': 'Plain Text',
                'text/csv': 'Comma Separated Values (CSV)',
                'text/html': 'HTML',
                'text/mediawiki': 'MediaWiki Markup',
                'application/xhtml+xml': 'XHTML',
                'application/postscript': 'PostScript',
                'application/illustrator': 'Adobe Illustrator File',
                'audio/x-aiff': 'AIFF Audio',
                'application/acp': 'Alfresco Content Package',
                'application/vnd.visio': 'Microsoft Visio',
                'application/vnd.adobe.xdp+xml': 'Adobe Acrobat XML Data Package',
                'audio/basic': 'Basic Audio',
                'video/ogg': 'Ogg Video',
                'audio/ogg': 'Ogg Audio',
                'audio/vorbis': 'Ogg Vorbis Audio',
                'application/ogg': 'Ogg Multiplex',
                'audio/x-flac': 'FLAC Audio',
                'video/webm': 'WebM Video',
                'video/x-msvideo': 'MS Video',
                'video/x-ms-asf': 'MS ASF Streaming Video',
                'video/x-ms-wmv': 'MS WMV Streaming Video',
                'audio/x-ms-wma': 'MS WMA Streaming Audio',
                'video/x-rad-screenplay': 'RAD Screen Display',
                'application/octet-stream': 'Binary File (Octet Stream)',
                'application/x-dosexec': 'Binary File',
                'image/cgm': 'CGM Image',
                'application/java': 'Java Class',
                'text/css': 'Style Sheet',
                'application/wordperfect': 'WordPerfect',
                'text/xml': 'XML',
                'image/gif': 'GIF Image',
                'application/x-gtar': 'GZIP Tarball',
                'application/x-gzip': 'GZIP',
                'text/calendar': 'iCalendar File',
                'image/ief': 'IEF Image',
                'image/bmp': 'Bitmap Image',
                'image/x-ms-bmp': 'MS Bitmap Image',
                'image/jpeg': 'JPEG Image',
                'image/svg+xml': 'Scalable Vector Graphics Image',
                'image/x-raw-adobe': 'Adobe Digital Negative Image',
                'image/x-raw-hasselblad': 'Hasselblad RAW Image',
                'image/x-raw-fuji': 'Fuji RAW Image',
                'image/x-raw-canon': 'Canon RAW Image',
                'image/x-raw-kodak': 'Kodak RAW Image',
                'image/x-raw-minolta': 'Minolta RAW Image',
                'image/x-raw-nikon': 'Nikon RAW Image',
                'image/x-raw-olympus': 'Olympus RAW Image',
                'image/x-raw-pentax': 'Pentax RAW Image',
                'image/x-raw-sony': 'Sony RAW Image',
                'image/x-raw-sigma': 'Sigma RAW Image',
                'image/x-raw-panasonic': 'Panasonic RAW Image',
                'image/x-raw-leica': 'Leica RAW Image',
                'image/x-raw-red': 'RED RAW Image',
                'application/x-javascript': 'JavaScript',
                'application/x-latex': 'LaTeX',
                'application/x-troff-man': 'Man Page',
                'video/mpeg': 'MPEG Video',
                'audio/mpeg': 'MPEG Audio',
                'audio/mp4': 'MPEG4 Audio',
                'video/mp4': 'MPEG4 Video',
                'video/x-m4v': 'MPEG4 Video (m4v)',
                'video/mpeg2': 'MPEG2 Video',
                'video/mp2t': 'MPEG Transport Stream',
                'video/quicktime': 'Quicktime Video',
                'video/3gpp': '3G Video',
                'video/3gpp2': '3G2 Video',
                'video/x-sgi-movie': 'SGI Video',
                'image/x-portable-bitmap': 'Portable Bitmap',
                'application/pdf': 'Adobe PDF Document',
                'image/x-portable-graymap': 'Greymap Image',
                'image/png': 'PNG Image',
                'image/x-portable-anymap': 'Anymap Image',
                'image/x-portable-pixmap': 'Pixmap Image',
                'image/x-cmu-raster': 'Raster Image',
                'image/x-rgb': 'RGB Image',
                'application/rtf': 'Rich Text Format',
                'text/richtext': 'Rich Text',
                'text/sgml': 'SGML (Human Readable)',
                'application/sgml': 'SGML (Machine Readable)',
                'application/x-sh': 'Shell Script',
                'application/vnd.adobe.air-application-installer-package+zip': 'Adobe AIR',
                'application/x-shockwave-flash': 'Shockwave Flash',
                'video/x-flv': 'Flash Video',
                'application/x-fla': 'Flash Source',
                'application/dita+xml': 'DITA',
                'application/x-tar': 'Tarball',
                'application/x-tex': 'Tex',
                'application/x-texinfo': 'Tex Info',
                'image/tiff': 'TIFF Image',
                'text/tab-separated-values': 'Tab Separated Values',
                'audio/x-wav': 'WAV Audio',
                'x-world/x-vrml': 'VRML',
                'image/x-xbitmap': 'XBitmap Image',
                'image/x-xpixmap': 'XPixmap Image',
                'image/x-xwindowdump': 'XWindow Dump',
                'application/x-compress': 'Z Compress',
                'application/zip': 'ZIP',
                'application/vnd.android.package-archive': 'Android Package',
                'image/vnd.dwg': 'AutoCAD Drawing',
                'image/x-dwt': 'AutoCAD Template',
                'message/rfc822': 'EMail',
                'application/vnd.ms-outlook': 'Microsoft Outlook Message',
                'application/msword': 'Microsoft Word',
                'application/vnd.ms-powerpoint': 'Microsoft PowerPoint',
                'application/vnd.ms-excel': 'Microsoft Excel',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'Microsoft Word 2007',
                'application/vnd.ms-word.document.macroenabled.12': 'Microsoft Word 2007 macro-enabled document',
                'application/vnd.openxmlformats-officedocument.wordprocessingml.template': 'Microsoft Word 2007 template',
                'application/vnd.ms-word.template.macroenabled.12': 'Microsoft Word 2007 macro-enabled document template',
                'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'Microsoft PowerPoint 2007',
                'application/vnd.ms-powerpoint.presentation.macroenabled.12': 'Microsoft PowerPoint 2007 macro-enabled presentation',
                'application/vnd.openxmlformats-officedocument.presentationml.slideshow': 'Microsoft PowerPoint 2007 slide show',
                'application/vnd.ms-powerpoint.slideshow.macroenabled.12': 'Microsoft PowerPoint 2007 macro-enabled slide show',
                'application/vnd.openxmlformats-officedocument.presentationml.template': 'Microsoft PowerPoint 2007 template',
                'application/vnd.ms-powerpoint.template.macroenabled.12': 'Microsoft PowerPoint 2007 macro-enabled presentation template',
                'application/vnd.ms-powerpoint.addin.macroenabled.12': 'Microsoft PowerPoint 2007 add-in',
                'application/vnd.openxmlformats-officedocument.presentationml.slide': 'Microsoft PowerPoint 2007 slide',
                'application/vnd.ms-powerpoint.slide.macroenabled.12': 'Microsoft PowerPoint 2007 macro-enabled slide',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'Microsoft Excel 2007',
                'application/vnd.openxmlformats-officedocument.spreadsheetml.template': 'Microsoft Excel template 2007',
                'application/vnd.ms-excel.sheet.macroenabled.12': 'Microsoft Excel 2007 macro-enabled workbook',
                'application/vnd.ms-excel.template.macroenabled.12': 'Microsoft Excel 2007 macro-enabled workbook template',
                'application/vnd.ms-excel.addin.macroenabled.12': 'Microsoft Excel 2007 add-in',
                'application/vnd.ms-excel.sheet.binary.macroenabled.12': 'Microsoft Excel 2007 binary workbook',
                'application/x-zip': 'Adobe Flex Project File',
                'application/x-indesign': 'Adobe InDesign Document',
                'application/vnd.apple.keynote': 'Apple iWork Keynote',
                'application/vnd.apple.pages': 'Apple iWork Pages',
                'application/vnd.apple.numbers': 'Apple iWork Numbers',
                'text/x-markdown': 'Markdown',
                'application/rss+xml': 'RSS',
                'text/x-java-source': 'Java Source File',
                'text/x-jsp': 'Java Server Page',
                'application/java-archive': 'Java Archive',
                'application/x-rar-compressed': 'RAR Archive',
                'application/vnd.oasis.opendocument.text': 'OpenDocument Text (OpenOffice 2.0)',
                'application/vnd.oasis.opendocument.text-template': 'OpenDocument Text Template',
                'application/vnd.oasis.opendocument.text-web': 'HTML Document Template',
                'application/vnd.oasis.opendocument.text-master': 'OpenDocument Master Document',
                'application/vnd.oasis.opendocument.graphics': 'OpenDocument Drawing',
                'application/vnd.oasis.opendocument.graphics-template': 'OpenDocument Drawing Template',
                'application/vnd.oasis.opendocument.presentation': 'OpenDocument Presentation',
                'application/vnd.oasis.opendocument.presentation-template': 'OpenDocument Presentation Template',
                'application/vnd.oasis.opendocument.spreadsheet': 'OpenDocument Spreadsheet',
                'application/vnd.oasis.opendocument.spreadsheet-template': 'OpenDocument Spreadsheet Template',
                'application/vnd.oasis.opendocument.chart': 'OpenDocument Chart',
                'application/vnd.oasis.opendocument.formula': 'OpenDocument Formula',
                'application/vnd.oasis.opendocument.database': 'OpenDocument Database',
                'application/vnd.oasis.opendocument.image': 'OpenDocument Image',
                'application/vnd.sun.xml.calc': 'OpenOffice 1.0/StarOffice6.0 Calc 6.0',
                'application/vnd.sun.xml.calc.template': 'OpenOffice 1.0/StarOffice6.0 Calc 6.0 Template',
                'application/vnd.sun.xml.draw': 'OpenOffice 1.0/StarOffice6.0 Draw 6.0',
                'application/vnd.sun.xml.impress': 'OpenOffice 1.0/StarOffice6.0 Impress 6.0',
                'application/vnd.sun.xml.impress.template': 'OpenOffice 1.0/StarOffice6.0 Impress 6.0 Template',
                'application/vnd.sun.xml.writer': 'OpenOffice 1.0/StarOffice6.0 Writer 6.0',
                'application/vnd.sun.xml.writer.template': 'OpenOffice 1.0/StarOffice6.0 Writer 6.0 Template',
                'application/vnd.stardivision.draw': 'StarDraw 5.x',
                'application/vnd.stardivision.calc': 'StarCalc 5.x',
                'application/vnd.stardivision.impress': 'StarImpress 5.x',
                'application/vnd.stardivision.impress-packed': 'StarImpress Packed 5.x',
                'application/vnd.stardivision.chart': 'StaChart 5.x',
                'application/vnd.stardivision.writer': 'StarWriter 5.x',
                'application/vnd.stardivision.writer-global': 'StarWriter 5.x global',
                'application/vnd.stardivision.math': 'StarMath 5.x',
                'aa': 'Afar',
                'ab': 'Abkhaz',
                'ae': 'Avestan',
                'af': 'Africanos',
                'ak': 'Akan',
                'am': 'Amharic',
                'an': 'Aragonés',
                'ar': 'Árabe',
                'as': 'Assamese',
                'av': 'Avaric',
                'ay': 'Aymara',
                'az': 'Azerbaijani',
                'ba': 'Bashkir',
                'be': 'Belarús',
                'bg': 'Búlgaro',
                'bh': 'Bihari',
                'bi': 'Bislama',
                'bm': 'Bambara',
                'bn': 'Bengalí',
                'bo': 'Tibetano',
                'br': 'Breton',
                'bs': 'Bosnian',
                'ca': 'Catalán',
                'ce': 'Chechenio',
                'ch': 'Chamorro',
                'co': 'Corso',
                'cr': 'Cree',
                'cs': 'Checo',
                'cu': 'Antiguo eslavo ',
                'cv': 'Chuvashia',
                'cy': 'Galés',
                'da': 'Danés',
                'de': 'Alemán',
                'dv': 'Dhivehi',
                'dz': 'Dzongkha',
                'ee': 'Ewe',
                'el': 'Modern Greek',
                'en': 'Inglés',
                'en-GB': 'Inglés Británico',
                'en_US': 'Inglés (EEUU)',
                'eo': 'Esperanto',
                'es': 'Español',
                'es-ES': 'Español (España)',
                'et': 'Estonio',
                'eu': 'Vasco',
                'fa': 'Persa',
                'ff': 'Fulah',
                'fi': 'Finlandés',
                'fj': 'Fiji',
                'fo': 'Faroese',
                'fr': 'Francés',
                'fy': 'Oeste de Frisia',
                'ga': 'Irlandés',
                'gd': 'Scottish Gaelic',
                'gl': 'Gallego',
                'gn': 'Guarani',
                'gu': 'Gujarati',
                'gv': 'Manx',
                'ha': 'Hausa',
                'he': 'Hebrew',
                'hi': 'Hindi',
                'ho': 'Hiri Motu',
                'hr': 'Croato',
                'ht': 'Haitian',
                'hu': 'Hungarian',
                'hy': 'Armenio',
                'hz': 'Herero',
                'ia': 'Interlingua',
                'id': 'Indonesio',
                'ie': 'Interlingue',
                'ig': 'Igbo',
                'ii': 'Sichuan Yi',
                'ik': 'Inupiaq',
                'io': 'Ido',
                'is': 'Islandés',
                'it': 'Italiano',
                'iu': 'Inuktitut',
                'ja': 'Japonés',
                'jv': 'Javanese',
                'ka': 'Georgiano',
                'kg': 'Kongo',
                'ki': 'Kikuyu',
                'kj': 'Kuanyama',
                'kk': 'Kazakh',
                'kl': 'Kalaallisut',
                'km': 'Central Khmer',
                'kn': 'Kannada',
                'ko': 'Coreano',
                'kr': 'Kanuri',
                'ks': 'Kashmiri',
                'ku': 'Kurdish',
                'kv': 'Komi',
                'kw': 'Cornish',
                'ky': 'Kirghiz',
                'la': 'Latin',
                'lb': 'Luxembourgish',
                'lg': 'Ganda',
                'li': 'Limburgan',
                'ln': 'Lingala',
                'lo': 'Lao',
                'lt': 'Lithuanian',
                'lu': 'Luba-Katanga',
                'lv': 'Letón',
                'mg': 'Malagasy',
                'mh': 'Marshallese',
                'mi': 'Maori',
                'mk': 'Macedonio',
                'ml': 'Malayalam',
                'mn': 'Mongolés',
                'mr': 'Marathi',
                'ms': 'Malay',
                'mt': 'Maltés',
                'my': 'Burmese',
                'na': 'Nauru',
                'nb': 'Norwegian Bokmål',
                'nd': 'North Ndebele',
                'ne': 'Nepali',
                'ng': 'Ndonga',
                'nl': 'Holandés',
                'nn': 'Noruego Nynorsk',
                'no': 'Noruego',
                'nr': 'South Ndebele',
                'nv': 'Navajo',
                'ny': 'Nyanja',
                'oc': 'Occitan',
                'oj': 'Ojibwa',
                'om': 'Oromo',
                'or': 'Oriya',
                'os': 'Ossetian',
                'pa': 'Panjabi',
                'pi': 'Pali',
                'pl': 'Polaco',
                'ps': 'Pushto',
                'pt': 'Portugués',
                'qu': 'Quechua',
                'rm': 'Romanche',
                'rn': 'Rundi',
                'ro': 'Rumano',
                'ru': 'Ruso',
                'rw': 'Kinyarwanda',
                'sa': 'Sanskrit',
                'sc': 'Sardinian',
                'sd': 'Sindhi',
                'se': 'Sami del norte',
                'sg': 'Sango',
                'sh': ' Serbo-Croatian',
                'si': 'Sinhala',
                'sk': 'Eslovaco',
                'sl': 'Esloveno',
                'sm': 'Samoan',
                'sn': 'Shona',
                'so': 'Somalí',
                'sq': 'Albanian',
                'sr': 'Serbian',
                'ss': 'Swati',
                'st': 'Southern Sotho',
                'su': 'Sundanese',
                'sv': 'Sueco',
                'sw': 'Swahili',
                'ta': 'Tamil',
                'te': 'Telugu',
                'tg': 'Tajik',
                'th': 'Tailandés',
                'ti': 'Tigrinya',
                'tk': 'Turkmen',
                'tl': 'Tagalo',
                'tn': 'Tswana',
                'to': 'Tonga (Islas Tonga)',
                'tr': 'Turkish',
                'ts': 'Tsonga',
                'tt': 'Tatar',
                'tw': 'Twi',
                'ty': 'Tahitian',
                'ug': 'Uighur',
                'uk': 'Ucraniano',
                'ur': 'Urdu',
                'uz': 'Uzbek',
                've': 'Venda',
                'vi': 'Vietnamita',
                'vo': 'Volapük',
                'wa': 'Walloon',
                'wo': 'Wolof',
                'xh': 'Xhosa',
                'yi': 'Yiddish',
                'yo': 'Yoruba',
                'za': 'Zhuang',
                'zh': 'Chino',
                'zu': 'Zulu',
                'Unknown': 'Desconocido'
            }
        }).config([
            '$routeProvider', '$httpProvider', '$translateProvider', 'SensefyTranslations', '$sceProvider', '$locationProvider', 'SensefySearchLogin', 'SensefySearchResponseFailedIsLogout', 'DEBUGmode',
            function ($routeProvider, $httpProvider, $translateProvider, SensefyTranslations, $sceProvider, $locationProvider, SensefySearchLogin, SensefySearchResponseFailedIsLogout, DEBUGmode) {
                var data, lang;
                $locationProvider.html5Mode(true);
                $sceProvider.enabled(false);

                for (lang in SensefyTranslations) {
                    data = SensefyTranslations[lang];
                    $translateProvider.translations(lang, data);
                }
                $translateProvider.preferredLanguage('en-us');

                $routeProvider.when('/login', {
                    templateUrl: 'views/login/login.html',
                    controller: 'LoginController'
                }).when('/', {
                    templateUrl: 'views/search.html',
                    controller: 'SearchController',
                    reloadOnSearch: false,
                    resolve: {
                        dataSources: function ($q, $rootScope, SemanticSearchService, $location) {
                            var deferrer;
                            //if ($rootScope.user !== null || $rootScope.user !== undefined) {
                            if ($rootScope.user !== null || $rootScope.user !== undefined) {
                                deferrer = $q.defer();
                                SemanticSearchService.search('*:*', 0, 0, "*", [], true).then(function (response) {
                                    return deferrer.resolve(response);
                                }, function (response) {
                                    deferrer.reject;
                                    document.location.href = SensefySearchLogin;
                                });

                                return deferrer.promise;
                            }
                            else {
                                if (SensefySearchResponseFailedIsLogout) {
                                    //$scope.$parent.logout();
                                    document.location.href = SensefySearchLogin;
                                    if (DEBUGmode) {
                                        console.log('dataSources: function ($q, $rootScope, SemanticSearchService, $location) is fired, but FAILED');
                                    }
                                }
                            }
                        }
                    }
                }).when('/browser', {
                    templateUrl: 'views/browser.html',
                    controller: 'RepoBrowserController'
                }).when('/mlt/:docId', {
                    templateUrl: 'views/mlt.html',
                    controller: 'MltController',
                    resolve: {
                        document: function ($window, $rootScope, $route, SemanticSearchService, $location, $q) {
                            var deferrer, docId, regExp;
                            regExp = new RegExp("\\[SL\\]", "g");
                            docId = $route.current.params.docId.replace(regExp, '/');
                            if (docId.substring(0, 4) === "Sent") {
                                docId = $window.encodeURIComponent(docId);
                                docId = docId.replace('%2F', '/', 'g');
                            }
                            deferrer = $q.defer();
                            if ($rootScope.user !== void 0) {
                                SemanticSearchService.search('id:"' + docId + '"', $rootScope.user.token, 0, 1).then(function (response) {
                                    return deferrer.resolve(response);
                                }, function (response) {
                                    deferrer.reject;
                                    return $location.path("/");
                                });
                                return deferrer.promise;
                            }
                        }
                    }
                }).when('/preview/:docId', {
                    templateUrl: 'views/preview.html',
                    controller: 'PreviewController'
                }).when('/imgSearch', {
                    templateUrl: 'views/imgSearch.html',
                    controller: 'ImageSearchController'
                }).otherwise
                ({
                    redirectTo: '/'
                });
                $httpProvider.defaults.useXDomain = true;
                //$httpProvider.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
                return delete $httpProvider.defaults.headers.common['X-Requested-With'];
            }
        ]).run([
            '$rootScope', '$location', '$window', '$http', '$translate', 'auth',
            function ($rootScope, $location, $window, $http, $translate, auth) {
                auth.init('/', '/login', '/logout');
                /*return $rootScope.$on('$routeChangeStart', function(event, next, current) {
                 $rootScope.loading = true;
                 $rootScope.searchParameters = $rootScope.searchParameters || $location.search();
                 if (next.originalPath !== "/login" && $rootScope.user === void 0) {
                 $location.path("/");
                 $location.search($location.search());
                 }
                 return window.translate = $translate;
                 });*/
            }
        ]);

}).call(this);